/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopCart: typeof import('./src/components/ShopCart.vue')['default']
    Stepper: typeof import('./src/components/Stepper.vue')['default']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTimePicker: typeof import('vant/es')['TimePicker']
  }
}
